spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/sber
    username: sber
    password: sber
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
        generate_statistics: true