spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    username: sber
    password: sber
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
