spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/sber
    username: sber
    password: sber
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update